tasks:
  - name: Gitpod Task
    init: |
      npm install
      npm i -D @playwright/test
      npx playwright install-deps
      npx playwright install
    command: | 
      echo "Run the test suite using the following command: URL=https://8080-adyenexampl-adyendotnet-1xxxxxxxxxx.ws-eu88.gitpod.io npx playwright test checkout"
      echo "The URL refers to the baseUrl of the application you want to test."